### ISSUE TITLE
Local planner - does not obey costmap rules

### ISSUE THREAD

**Issue by IsaacHook** [ursa-drone/ursa-server#14]
- In particular when global planner is around corners.  Likely due to how robot motion is generated from local plan.
![screenshot from 2017-07-31 14-25-31](https://user-images.githubusercontent.com/12621911/28762732-2d0bebbc-75fc-11e7-90af-9fbaf8d7ca76.png)

**Comment by IsaacHook** [comment]
> Likely due to how robot motion is generated from local plan
- Need to add simulation of points so navigation stack can check points in costmap

**Comment by lachyd** [comment]
This behaviour is in the obstacle_costs_ critic. The local planner obstacle critic checks each point in the robot footprint for 'fatal collision' i.e. hitting a wall. So basically it lets the drone cut very closely to the wall - within one radius of a collision. 

What we need is to work out an appropriate cost function trade-off between progressing along the global plan and flying near walls. Note that this gives the added benefit that, when flying near walls, the drone will not fly as fast since the set-point will be closer to the drone. Steps to rectify:

- Make our own version of the obstacle_costs_ critic which returns a numeric cost value in order to prefer trajectories further from the wall. Suggest returning the worst scoring point on a trajectory as per the costmap. Negative values should still be returned if the cost is above 128 since this indicates a possible collision.
- Tune the gain on the obstacle_costs_ critic and the goal_costs_ critic. Suggest experimenting with the goal_costs_ critic as an exponential function rather than a linear function. Also suggest expanding the inflation radius for the local planner.

**Comment by IsaacHook** [comment]
current behaviour:
    - global planner recognises inflation radius and plans around it
    - local planner avoids trajectories that pass through "w-space" (http://wiki.ros.org/costmap_2d?distro=lunar#costmap_2d.2BAC8-layered.Subscribed_Topics)
![screenshot from 2017-08-03 12-49-16](https://user-images.githubusercontent.com/12621911/28903797-3112bd4e-784a-11e7-9f14-acfa67822e35.png)

**Comment by IsaacHook** [comment]
- Local trajectories around corner give same obstacle cost function because the robot footprint is used to calculate the cost, not just if the trajectory passes through a high cost area

![screenshot from 2017-08-07 13-49-21](https://user-images.githubusercontent.com/12621911/29011551-51c34844-7b77-11e7-9c88-8f7fb8212609.png)

**Comment by lachyd** [comment]
Fixed in corners branch and merged.
